on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
       - name: Install dependencies
       - run: cd /home/runner/work/CCP4-Web-Assembly/
       - run:  mv CCP4-Web-Assembly ccp4_wasm
       - run:  echo $(ls ccp4_wasm)
       - run:  cd /home/runner/work/CCP4-Web-Assembly/ccp4_wasm
       - run:  echo $(ls  $pwd)
