on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
       - name: One
         run: ls
       - name: Two     
         working-directory: /home/runner/work/
         run:  ls
       - name: Three     
         working-directory: /home/runner/work/CCP4-Web-Assembly/
         run:  ls
       - name: Four     
         working-directory: /home/runner/work/CCP4-Web-Assembly/ccp4_wasm
         run:  ls

