on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3  
     - name: Install dependencies
       run: |
         sudo apt-get install -y bzr cmake libz-dev
         cd ..
         mv CCP4-Web-Assembly ccp4_wasm
         cd ccp4_wasm
         ./get_sources
     - uses: mymindstorm/setup-emsdk@v11     
     - name: Create emscripten bindings
       working-directory: /home/runner/work/CCP4-Web-Assembly/ccp4_wasm
       run: |
         emcmake cmake .
         emmake make
     - uses: actions/setup-node@v3
     - name: Run tests
       working-directory: /home/runner/work/CCP4-Web-Assembly/ccp4_wasm
       run: |
         cd tests
         npm install
         npm test
