on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
       - name: One
         run: cd /home/runner/work/CCP4-Web-Assembly/
       - name: Two
         run:  mv CCP4-Web-Assembly ccp4_wasm
       - name: Three     
         run:  echo $(ls ccp4_wasm)
       - name: Four       
         run:  cd /home/runner/work/CCP4-Web-Assembly/ccp4_wasm
       - name: Five       
         run:  echo $(ls  $pwd)
