name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
     - uses: mymindstorm/setup-emsdk@v11
     - name: Get sources
       run: |
         ./get_sources
     - name: emscriptem bndings
     - run: |
         emcmake cmake .
         emmake make
     - name: Run tests
     - run: |
         cd reac_app
         npm test
         
