on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
       - name: One
         run: | 
               cd /home/runner/work/CCP4-Web-Assembly/
               mv CCP4-Web-Assembly ccp4_wasm
       - name: Three     
         working-directory: /home/runner/work/CCP4-Web-Assembly/
         run:  echo $(ls ccp4_wasm)
       - name: Four    
         working-directory: /home/runner/work/CCP4-Web-Assembly/ccp4_wasm    
         run:  echo $(ls  $pwd)
