on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - name: Run tests
         run: |
           sudo apt-get install -y bzr nodejs npm         
           cd /home/runner/work/CCP4-Web-Assembly/
           mv CCP4-Web-Assembly ccp4_wasm
           git clone https://github.com/emscripten-core/emsdk.git
           cd /home/runner/work/CCP4-Web-Assembly/emsdk/
           ./emsdk install latest
           ./emsdk activate latest
           source ./emsdk_env.sh             
           cd /home/runner/work/CCP4-Web-Assembly/ccp4_wasm
           ./get_sources
           emcmake cmake .
           emmake make
           cd /home/runner/work/CCP4-Web-Assembly/ccp4_wasm/tests
           npm install
           npm test -sEXIT_RUNTIME=1       
